import type { ThemeModel } from "@/theme/model.ts";
import { mix, transparent, withAlpha } from "@/theme/palette.ts";
import type { ColorMap } from "@/theme/types.ts";

export const editorColors = ({ accent, surfaces, syntax }: ThemeModel): ColorMap => ({
  "editor.background": surfaces.editor,
  "editor.foreground": surfaces.fg,
  "editorGutter.background": surfaces.editor,
  "editorLineNumber.foreground": surfaces.subtle,
  "editorLineNumber.activeForeground": surfaces.muted,
  "editor.lineHighlightBackground": surfaces.chrome1,
  "editor.lineHighlightBorder": transparent(),
  "editorIndentGuide.background1": withAlpha(surfaces.lineStrong, surfaces.isDark ? 0.22 : 0.5),
  "editorIndentGuide.activeBackground1": surfaces.ghost,
  "editorRuler.foreground": withAlpha(surfaces.lineStrong, 0.45),
  "editorWhitespace.foreground": withAlpha(surfaces.muted, 0.28),
  "editorCursor.foreground": accent.main,
  "editorCursor.background": surfaces.editor,
  "editor.selectionBackground": surfaces.selection,
  "editor.selectionHighlightBackground": surfaces.selectionSoft,
  "editor.inactiveSelectionBackground": withAlpha(surfaces.inverse, surfaces.isDark ? 0.04 : 0.05),
  "editor.wordHighlightBackground": surfaces.selectionSoft,
  "editor.wordHighlightStrongBackground": withAlpha(accent.main, surfaces.isDark ? 0.13 : 0.1),
  "editor.findMatchBackground": withAlpha(accent.main, surfaces.isDark ? 0.32 : 0.22),
  "editor.findMatchBorder": accent.border,
  "editor.findMatchHighlightBackground": surfaces.selectionSoft,
  "editor.findMatchHighlightBorder": withAlpha(surfaces.inverse, surfaces.isDark ? 0.16 : 0.12),
  "editor.rangeHighlightBackground": withAlpha(surfaces.inverse, surfaces.isDark ? 0.04 : 0.05),
  "editor.hoverHighlightBackground": withAlpha(surfaces.inverse, surfaces.isDark ? 0.04 : 0.05),
  "editorLink.activeForeground": accent.main,
  "editorCodeLens.foreground": syntax.comment,
  "editorBracketMatch.background": withAlpha(accent.main, surfaces.isDark ? 0.12 : 0.1),
  "editorBracketMatch.border": accent.border,
  "editor.snippetTabstopHighlightBackground": withAlpha(syntax.added, surfaces.isDark ? 0.18 : 0.12),
});

export const bracketColors = ({ surfaces, syntax }: ThemeModel): ColorMap => ({
  "editorBracketHighlight.foreground1": mix(syntax.constant, surfaces.muted, 0.42),
  "editorBracketHighlight.foreground2": mix(syntax.operator, surfaces.muted, 0.42),
  "editorBracketHighlight.foreground3": mix(syntax.type, surfaces.muted, 0.42),
  "editorBracketHighlight.unexpectedBracket.foreground": syntax.invalid,
  "editorBracketPairGuide.background1": withAlpha(syntax.constant, 0.04),
  "editorBracketPairGuide.background2": withAlpha(syntax.operator, 0.04),
  "editorBracketPairGuide.background3": withAlpha(syntax.type, 0.04),
  "editorBracketPairGuide.background4": withAlpha(syntax.info, 0.04),
  "editorBracketPairGuide.background5": withAlpha(syntax.added, 0.04),
  "editorBracketPairGuide.background6": withAlpha(syntax.property, 0.04),
  "editorBracketPairGuide.activeBackground1": withAlpha(syntax.constant, 0.12),
  "editorBracketPairGuide.activeBackground2": withAlpha(syntax.operator, 0.12),
  "editorBracketPairGuide.activeBackground3": withAlpha(syntax.type, 0.12),
  "editorBracketPairGuide.activeBackground4": withAlpha(syntax.info, 0.12),
  "editorBracketPairGuide.activeBackground5": withAlpha(syntax.added, 0.12),
  "editorBracketPairGuide.activeBackground6": withAlpha(syntax.property, 0.12),
});
