import type { ThemeModel } from "@/theme/model.ts";
import type { ColorMap } from "@/theme/types.ts";

export const symbolColors = ({ surfaces, syntax }: ThemeModel): ColorMap => ({
  "symbolIcon.arrayForeground": syntax.constant,
  "symbolIcon.booleanForeground": syntax.constant,
  "symbolIcon.classForeground": syntax.class,
  "symbolIcon.colorForeground": syntax.special,
  "symbolIcon.constantForeground": syntax.constant,
  "symbolIcon.constructorForeground": syntax.function,
  "symbolIcon.enumeratorForeground": syntax.type,
  "symbolIcon.enumeratorMemberForeground": syntax.constant,
  "symbolIcon.eventForeground": syntax.operator,
  "symbolIcon.fieldForeground": syntax.property,
  "symbolIcon.fileForeground": surfaces.fg,
  "symbolIcon.folderForeground": surfaces.muted,
  "symbolIcon.functionForeground": syntax.function,
  "symbolIcon.interfaceForeground": syntax.interface,
  "symbolIcon.keyForeground": syntax.attribute,
  "symbolIcon.keywordForeground": syntax.keyword,
  "symbolIcon.methodForeground": syntax.method,
  "symbolIcon.moduleForeground": syntax.string,
  "symbolIcon.namespaceForeground": syntax.string,
  "symbolIcon.nullForeground": syntax.constant,
  "symbolIcon.numberForeground": syntax.number,
  "symbolIcon.objectForeground": syntax.class,
  "symbolIcon.operatorForeground": syntax.operator,
  "symbolIcon.packageForeground": syntax.string,
  "symbolIcon.propertyForeground": syntax.property,
  "symbolIcon.referenceForeground": syntax.class,
  "symbolIcon.snippetForeground": syntax.special,
  "symbolIcon.stringForeground": syntax.string,
  "symbolIcon.structForeground": syntax.class,
  "symbolIcon.textForeground": surfaces.fg,
  "symbolIcon.typeParameterForeground": syntax.type,
  "symbolIcon.unitForeground": syntax.constant,
  "symbolIcon.variableForeground": surfaces.fg,
});
