import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";

import {
  borderVariants,
  defaultBorders,
  defaultDimming,
  defaultPanels,
  defaultShadeForMode,
  defaultTerminal,
  modes,
  shadeVariants,
  syntaxVariants,
  type Mode,
  type ShadeVariant,
  type SyntaxVariant,
} from "@/config.ts";
import { insertDiffMarkers, umbreDiffMarkers, type MarkdownItWithCore } from "@/markdown/diff-markers.ts";
import { highlightFileTree, isFileTree, umbreFileTrees } from "@/markdown/file-tree.ts";
import {
  markdownColorContributions,
  markdownColorId,
  markdownColors,
  markdownTextColors,
} from "@/theme/markdown.ts";
import { createThemeModel } from "@/theme/model.ts";
import { workbenchColors } from "@/theme/workbench/index.ts";
import { wcagContrast } from "culori";
import MarkdownIt from "markdown-it";

const model = (
  syntaxVariant: SyntaxVariant = syntaxVariants[0],
  mode: Mode = "dark",
  shade: ShadeVariant = defaultShadeForMode(mode),
) =>
  createThemeModel({
    mode,
    shade,
    accentFamily: "amber",
    dim: defaultDimming,
    panels: defaultPanels,
    terminal: defaultTerminal,
    borders: defaultBorders,
    syntaxVariant,
  });

const stylesheet = readFileSync(new URL("../../assets/markdown-preview.css", import.meta.url), "utf8");

describe("Umbre Markdown colors", () => {
  test("every contributed color is generated by the theme", () => {
    const colors = markdownColors(model());
    for (const contribution of markdownColorContributions()) expect(colors[contribution.id]).toBeDefined();
  });

  test("color ids have one dot, because webviews only replace the first dot in variable names", () => {
    for (const { id } of markdownColorContributions()) expect(id.split(".")).toHaveLength(2);
  });

  test("the stylesheet only reads registered Umbre colors", () => {
    const registered = new Set(
      markdownColorContributions().map((color) => `--vscode-${color.id.replace(".", "-")}`),
    );
    const used = new Set(stylesheet.match(/--vscode-umbreMarkdown-[\w-]+/g) ?? []);
    expect(used.size).toBeGreaterThan(0);
    for (const variable of used) expect(registered.has(variable)).toBe(true);
  });

  test("code block colors follow the selected syntax scheme", () => {
    const [ember, flare] = syntaxVariants;
    const keyword = markdownColorId("syntaxKeyword");
    expect(markdownColors(model(ember))[keyword]).toBe(model(ember).syntax.keyword);
    expect(markdownColors(model(ember))[keyword]).not.toBe(markdownColors(model(flare))[keyword]);
  });

  test("links, inline code, muted text, and alerts read on every Markdown surface in every mode and shade", () => {
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        const themeModel = model(syntaxVariants[0], mode, shade);
        const colors = { ...markdownColors(themeModel), ...markdownTextColors(themeModel) };
        const surfaces = [
          themeModel.surfaces.editor,
          colors["textCodeBlock.background"] ?? "",
          colors["textBlockQuote.background"] ?? "",
          colors["textPreformat.background"] ?? "",
        ];
        const readable = [
          colors["textLink.foreground"],
          colors["textPreformat.foreground"],
          ...["muted", "warning", "note"].map((name) => colors[markdownColorId(name)]),
        ];
        for (const color of readable) {
          for (const surface of surfaces) {
            expect(wcagContrast(color ?? "", surface), `${mode} ${shade.id}`).toBeGreaterThanOrEqual(4.5);
          }
        }
      }
    }
  });

  test("structure stays visible in every mode, shade, border level, and syntax scheme", () => {
    const minimums = {
      rule: 1.6,
      softRule: 1.3,
      tableRule: 1.2,
      marker: 3,
    };
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        for (const borders of borderVariants) {
          for (const syntaxVariant of syntaxVariants) {
            const themeModel = createThemeModel({
              mode,
              shade,
              accentFamily: "amber",
              dim: defaultDimming,
              panels: defaultPanels,
              terminal: defaultTerminal,
              borders,
              syntaxVariant,
            });
            const colors = markdownColors(themeModel);
            for (const [name, minimum] of Object.entries(minimums)) {
              const contrast = wcagContrast(colors[markdownColorId(name)] ?? "", themeModel.surfaces.editor);
              expect(
                contrast,
                `${mode} ${shade.id} ${borders.id} ${syntaxVariant.id} ${name}`,
              ).toBeGreaterThanOrEqual(minimum);
            }
          }
        }
      }
    }
  });

  test("the split-editor divider stays visible on every shade and border level", () => {
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        for (const borders of borderVariants) {
          const themeModel = createThemeModel({
            mode,
            shade,
            accentFamily: "amber",
            dim: defaultDimming,
            panels: defaultPanels,
            terminal: defaultTerminal,
            borders,
            syntaxVariant: syntaxVariants[0],
          });
          const divider = workbenchColors(themeModel)["editorGroup.border"] ?? "";
          const label = `${mode} ${shade.id} ${borders.id}`;
          expect(wcagContrast(divider, themeModel.surfaces.editor), label).toBeGreaterThanOrEqual(1.3);
        }
      }
    }
  });

  test("diagram strokes stay visible on every shade", () => {
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        const themeModel = model(syntaxVariants[0], mode, shade);
        const line = workbenchColors(themeModel)["chart.line"] ?? "";
        expect(wcagContrast(line, themeModel.surfaces.editor), `${mode} ${shade.id}`).toBeGreaterThanOrEqual(
          3,
        );
      }
    }
  });

  test("chart fills keep their labels readable and stand out from the page", () => {
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        const themeModel = model(syntaxVariants[0], mode, shade);
        const colors = workbenchColors(themeModel);
        for (const name of ["red", "blue", "yellow", "orange", "green", "purple"]) {
          const fill = colors[`charts.${name}`] ?? "";
          const label = `${mode} ${shade.id} ${name}`;
          expect(wcagContrast(fill, themeModel.surfaces.fg), label).toBeGreaterThanOrEqual(4.5);
          expect(wcagContrast(fill, themeModel.surfaces.editor), label).toBeGreaterThanOrEqual(1.4);
        }
      }
    }
  });

  test("the stylesheet has no hard-coded colors and stays scoped to Umbre", () => {
    expect(stylesheet).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    const selectors = stylesheet
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/@media[^{]*\{/g, "")
      .split("}")
      .map((block) => block.split("{")[0]?.trim() ?? "")
      .filter(Boolean);
    // The page root itself is scoped through the Umbre body it contains.
    const scope =
      /^:root(?::has\(> body\[data-vscode-theme-id="Umbre"\]\)| body\[data-vscode-theme-id="Umbre"\])/;
    for (const selector of selectors) {
      for (const part of selector.split(/,\s*(?![^(]*\))/)) {
        expect(part.replace(/\s+/g, " ")).toMatch(scope);
      }
    }
  });
});

describe("Umbre directory trees", () => {
  const tree = ["views/", "├── apps/", "│   └── prism/   # 🟩 workspace application", "└── README.md"].join(
    "\n",
  );

  test("recognizes tree listings only in plain and shell fences", () => {
    expect(isFileTree(tree, "text")).toBe(true);
    expect(isFileTree(tree, "")).toBe(true);
    expect(isFileTree(tree, "ts")).toBe(false);
    expect(isFileTree("echo hi\nls -la", "bash")).toBe(false);
  });

  test("marks guides, folders, files, and comments", () => {
    const html = highlightFileTree(tree);
    expect(html).toContain('<span class="umbre-tree-folder">views/</span>');
    expect(html).toContain('<span class="umbre-tree-folder">prism/</span>');
    expect(html).toContain('<span class="umbre-tree-file">README.md</span>');
    expect(html).toContain('<span class="umbre-tree-comment"># 🟩 workspace application</span>');
  });
});

describe("Umbre Markdown diff markers", () => {
  const start = (id: number): string => `<span data-diff-start="${id}"></span>`;
  const end = (id: number): string => `<span data-diff-end="${id}"></span>`;
  const render = (source: string, active = true, env: object = {}, replaceTokens = false): string => {
    const plain = new MarkdownIt({ html: true });
    // Like the footnote plugin, which hands back a new token list at the end of parsing.
    if (replaceTokens)
      plain.core.ruler.push("replace_tokens", (state) => void (state.tokens = [...state.tokens]));
    const md = plain as unknown as MarkdownItWithCore;
    const isActive = (): boolean => active;
    return (umbreDiffMarkers(umbreFileTrees(md, isActive), isActive) as unknown as MarkdownIt).render(
      source,
      env,
    );
  };

  test("keeps changes in a tree listing as markers, not text", () => {
    const html = render(
      ["```text", "src/", `├── a.ts`, `${start(1)}│   └── placement/${end(1)}`, "└── b.ts", "```"].join("\n"),
    );
    expect(html).not.toContain("&lt;span");
    expect(html).toContain('class="umbre-tree-folder"');
    expect(html).toContain(
      `<span class="umbre-tree-guide">${start(1)}│   └── </span><span class="umbre-tree-folder">placement/</span>${end(1)}`,
    );
    expect(html).toContain(start(1));
    expect(html).toContain(end(1));
  });

  test("keeps changes in highlighted code and inline code as markers", () => {
    const html = render(
      [
        "```ts",
        `const ${start(0)}value${end(0)} = 1;`,
        "```",
        "",
        `Use \`${start(2)}a<b${end(2)}\` here.`,
      ].join("\n"),
    );
    expect(html).not.toContain("&lt;span");
    expect(html).toContain(`const ${start(0)}value${end(0)} = 1;`);
    expect(html).toContain(`<code>${start(2)}a&lt;b${end(2)}</code>`);
  });

  test("never hides block syntax behind a marker", () => {
    const html = render(
      [
        `${start(0)}## Title${end(0)}`,
        "",
        `${start(1)}\`\`\`ts${end(1)}`,
        "let a = 1;",
        `${start(2)}\`\`\`${end(2)}`,
        "",
        `${start(3)}- item${end(3)}`,
      ].join("\n"),
    );
    expect(html).toContain(`<h2>${start(0)}Title${end(0)}</h2>`);
    expect(html).toContain('<pre><code class="language-ts">let a = 1;');
    expect(html).toContain(`<li>${start(3)}item${end(3)}</li>`);
  });

  test("keeps quoted fences and syntax-like code lines intact", () => {
    const html = render(
      [
        `> ${start(0)}\`\`\`ts${end(0)}`,
        "> let a = 1;",
        "> ```",
        "",
        "```text",
        `${start(1)}---${end(1)}`,
        "```",
      ].join("\n"),
    );
    expect(html).toContain('<blockquote>\n<pre><code class="language-ts">let a = 1;');
    expect(html).toContain(`<code class="language-text">${start(1)}---${end(1)}`);
  });

  test("follows Markdown's own block structure in lists and quotes", () => {
    const listFence = render(["- ```text", `  ${start(0)}---${end(0)}`, "  ```"].join("\n"));
    expect(listFence).toContain(`<code class="language-text">${start(0)}---${end(0)}`);

    const afterQuote = render(["> ```", "> code", "", `${start(1)}### New${end(1)}`].join("\n"));
    expect(afterQuote).toContain(`<h3>${start(1)}New${end(1)}</h3>`);
  });

  test("keeps working when a plugin replaces the token list", () => {
    const html = render(["```ts", `const ${start(0)}a${end(0)} = 1;`, "```"].join("\n"), true, {}, true);
    expect(html).toContain(`const ${start(0)}a${end(0)} = 1;`);
  });

  test("tells code from syntax by what the parser consumed", () => {
    const unclosed = render(["```text", "line", `    ${start(0)}\`\`\`${end(0)}`].join("\n"));
    expect(unclosed).toContain(`    ${start(0)}\`\`\`${end(0)}`);

    const indented = render(["Text", "", `    ${start(1)}> new${end(1)}`].join("\n"));
    expect(indented).toContain(`<pre><code>${start(1)}&gt; new${end(1)}`);
  });

  test("keeps table rows, links, headings, and inline code intact", () => {
    const table = render(["| a | b |", "| --- | --- |", `${start(0)}| c | d |${end(0)}`].join("\n"));
    expect(table).toContain(`<td>${start(0)}c</td>\n<td>d${end(0)}</td>`);

    const link = render(`See [site](${start(1)}https://example.org${end(1)}).`);
    expect(link).toContain('<a href="https://example.org">site</a>');
    expect(link).not.toContain("](");

    const heading = render(`## Title ${start(2)}new${end(2)} ##`);
    expect(heading).toContain(`<h2>Title ${start(2)}new${end(2)}</h2>`);

    const code = render(`Use \` ${start(3)}a${end(3)} \` here.`);
    expect(code.replace(/<span data-diff-(?:start|end)="\d+"><\/span>/g, "")).toContain("<code>a</code>");
  });

  test("never breaks references that span blocks", () => {
    const html = render(
      [
        `See [site][${start(0)}id${end(0)}].`,
        "",
        "```ts",
        `const ${start(1)}a${end(1)} = 1;`,
        "```",
        "",
        "[id]: https://example.org",
      ].join("\n"),
    );
    expect(html).toContain('<a href="https://example.org">site</a>');
    expect(html).toContain(`const ${start(1)}a${end(1)} = 1;`);
  });

  test("leaves ordinary previews untouched, even with marker-like text", () => {
    const source = [
      "Example:",
      "",
      `    ${start(9)}---${end(9)}`,
      "",
      "```html",
      `${start(0)}\`\`\`${end(0)}`,
      "```",
    ].join("\n");
    const document = { currentDocument: "file:///docs/example.md" };
    expect(render(source, true, document)).toBe(render(source, false, document));
  });

  test("renders marker-like text an author wrote exactly as written outside a diff", () => {
    const source = ["```html", `<p>${start(0)}Documented${end(0)}</p>`, "```"].join("\n");
    const html = render(source, true, { currentDocument: "file:///docs/example.md" });
    expect(html).toContain("&lt;span data-diff-start=&quot;0&quot;&gt;&lt;/span&gt;Documented");
  });

  test("leaves other themes' rendering alone", () => {
    expect(render(["```ts", `const ${start(0)}a${end(0)} = 1;`, "```"].join("\n"), false)).toContain(
      "&lt;span",
    );
  });

  test("counts HTML entities as one character", () => {
    expect(insertDiffMarkers("a&lt;b", [{ offset: 2, html: "|" }])).toBe("a&lt;|b");
    expect(insertDiffMarkers("<b>ab</b>\n", [{ offset: 2, html: "|" }])).toBe("<b>ab</b>|\n");
  });
});
