import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";

import {
  borderVariants,
  defaultBorders,
  defaultDimming,
  defaultPanels,
  defaultShadeForMode,
  defaultTerminal,
  modes,
  shadeVariants,
  syntaxVariants,
  type Mode,
  type ShadeVariant,
  type SyntaxVariant,
} from "@/config.ts";
import { highlightFileTree, isFileTree } from "@/markdown/file-tree.ts";
import {
  markdownColorContributions,
  markdownColorId,
  markdownColors,
  markdownTextColors,
} from "@/theme/markdown.ts";
import { createThemeModel } from "@/theme/model.ts";
import { workbenchColors } from "@/theme/workbench/index.ts";
import { wcagContrast } from "culori";

const model = (
  syntaxVariant: SyntaxVariant = syntaxVariants[0],
  mode: Mode = "dark",
  shade: ShadeVariant = defaultShadeForMode(mode),
) =>
  createThemeModel({
    mode,
    shade,
    accentFamily: "amber",
    dim: defaultDimming,
    panels: defaultPanels,
    terminal: defaultTerminal,
    borders: defaultBorders,
    syntaxVariant,
  });

const stylesheet = readFileSync(new URL("../../assets/markdown-preview.css", import.meta.url), "utf8");

describe("Umbre Markdown colors", () => {
  test("every contributed color is generated by the theme", () => {
    const colors = markdownColors(model());
    for (const contribution of markdownColorContributions()) expect(colors[contribution.id]).toBeDefined();
  });

  test("color ids have one dot, because webviews only replace the first dot in variable names", () => {
    for (const { id } of markdownColorContributions()) expect(id.split(".")).toHaveLength(2);
  });

  test("the stylesheet only reads registered Umbre colors", () => {
    const registered = new Set(
      markdownColorContributions().map((color) => `--vscode-${color.id.replace(".", "-")}`),
    );
    const used = new Set(stylesheet.match(/--vscode-umbreMarkdown-[\w-]+/g) ?? []);
    expect(used.size).toBeGreaterThan(0);
    for (const variable of used) expect(registered.has(variable)).toBe(true);
  });

  test("code block colors follow the selected syntax scheme", () => {
    const [ember, flare] = syntaxVariants;
    const keyword = markdownColorId("syntaxKeyword");
    expect(markdownColors(model(ember))[keyword]).toBe(model(ember).syntax.keyword);
    expect(markdownColors(model(ember))[keyword]).not.toBe(markdownColors(model(flare))[keyword]);
  });

  test("links, inline code, muted text, and alerts read on every Markdown surface in every mode and shade", () => {
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        const themeModel = model(syntaxVariants[0], mode, shade);
        const colors = { ...markdownColors(themeModel), ...markdownTextColors(themeModel) };
        const surfaces = [
          themeModel.surfaces.editor,
          colors["textCodeBlock.background"] ?? "",
          colors["textBlockQuote.background"] ?? "",
          colors["textPreformat.background"] ?? "",
        ];
        const readable = [
          colors["textLink.foreground"],
          colors["textPreformat.foreground"],
          ...["muted", "warning", "note"].map((name) => colors[markdownColorId(name)]),
        ];
        for (const color of readable) {
          for (const surface of surfaces) {
            expect(wcagContrast(color ?? "", surface), `${mode} ${shade.id}`).toBeGreaterThanOrEqual(4.5);
          }
        }
      }
    }
  });

  test("structure stays visible in every mode, shade, border level, and syntax scheme", () => {
    const minimums = {
      rule: 1.6,
      softRule: 1.3,
      tableRule: 1.2,
      marker: 3,
    };
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        for (const borders of borderVariants) {
          for (const syntaxVariant of syntaxVariants) {
            const themeModel = createThemeModel({
              mode,
              shade,
              accentFamily: "amber",
              dim: defaultDimming,
              panels: defaultPanels,
              terminal: defaultTerminal,
              borders,
              syntaxVariant,
            });
            const colors = markdownColors(themeModel);
            for (const [name, minimum] of Object.entries(minimums)) {
              const contrast = wcagContrast(colors[markdownColorId(name)] ?? "", themeModel.surfaces.editor);
              expect(
                contrast,
                `${mode} ${shade.id} ${borders.id} ${syntaxVariant.id} ${name}`,
              ).toBeGreaterThanOrEqual(minimum);
            }
          }
        }
      }
    }
  });

  test("diagram strokes stay visible on every shade", () => {
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        const themeModel = model(syntaxVariants[0], mode, shade);
        const line = workbenchColors(themeModel)["chart.line"] ?? "";
        expect(wcagContrast(line, themeModel.surfaces.editor), `${mode} ${shade.id}`).toBeGreaterThanOrEqual(
          3,
        );
      }
    }
  });

  test("chart fills keep their labels readable and stand out from the page", () => {
    for (const mode of modes) {
      for (const shade of shadeVariants) {
        const themeModel = model(syntaxVariants[0], mode, shade);
        const colors = workbenchColors(themeModel);
        for (const name of ["red", "blue", "yellow", "orange", "green", "purple"]) {
          const fill = colors[`charts.${name}`] ?? "";
          const label = `${mode} ${shade.id} ${name}`;
          expect(wcagContrast(fill, themeModel.surfaces.fg), label).toBeGreaterThanOrEqual(4.5);
          expect(wcagContrast(fill, themeModel.surfaces.editor), label).toBeGreaterThanOrEqual(1.4);
        }
      }
    }
  });

  test("the stylesheet has no hard-coded colors and stays scoped to Umbre", () => {
    expect(stylesheet).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    const selectors = stylesheet
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/@media[^{]*\{/g, "")
      .split("}")
      .map((block) => block.split("{")[0]?.trim() ?? "")
      .filter(Boolean);
    for (const selector of selectors) {
      for (const part of selector.split(/,\s*(?![^(]*\))/)) {
        expect(part.replace(/\s+/g, " ")).toStartWith(':root body[data-vscode-theme-id="Umbre"]');
      }
    }
  });
});

describe("Umbre directory trees", () => {
  const tree = ["views/", "├── apps/", "│   └── prism/   # 🟩 workspace application", "└── README.md"].join(
    "\n",
  );

  test("recognizes tree listings only in plain and shell fences", () => {
    expect(isFileTree(tree, "text")).toBe(true);
    expect(isFileTree(tree, "")).toBe(true);
    expect(isFileTree(tree, "ts")).toBe(false);
    expect(isFileTree("echo hi\nls -la", "bash")).toBe(false);
  });

  test("marks guides, folders, files, and comments", () => {
    const html = highlightFileTree(tree);
    expect(html).toContain('<span class="umbre-tree-folder">views/</span>');
    expect(html).toContain('<span class="umbre-tree-folder">prism/</span>');
    expect(html).toContain('<span class="umbre-tree-file">README.md</span>');
    expect(html).toContain('<span class="umbre-tree-comment"># 🟩 workspace application</span>');
  });
});
